apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  secretName: {{ .Values.listeners.https.certificateSecret }}
  issuerRef:
    name: {{ .Values.certificate.issuerName }}
    kind: {{ .Values.certificate.issuerKind }}
  dnsNames:
    {{- range .Values.certificate.domains }}
    - {{ . }}
    {{- end }}
