apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  gatewayClassName: alb
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      port: {{ .Values.listeners.https.port }}
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: {{ .Values.listeners.https.certificateSecret }}
{{- if .Values.listeners.https.acmCertificateArn }}
        options:
          application-networking.k8s.aws/certificate-arn: "{{ .Values.listeners.https.acmCertificateArn }}"
{{- end }}
      allowedRoutes:
        namespaces:
          from: Same
