replicaCount: 1

image:
  repository: 522868276919.dkr.ecr.eu-central-1.amazonaws.com/voting-app-worker
  tag: latest
  pullPolicy: IfNotPresent

env:
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  DB_HOST: postgres-postgresql
  DB_PORT: "5432"
  DB_USER: postgres
  DB_NAME: postgres

existingSecret: ""

secretEnv: {}
# Example:
# secretEnv:
#   DB_PASSWORD:
#     secretName: postgres-password
#     key: postgres-password

resources: {}
