apiVersion: v1
kind: Secret
metadata:
  name: voting-app-realm
  namespace: {{ .Release.Namespace }}
  labels:
    app: keycloak
type: Opaque
stringData:
  voting-app-realm.json: |
{{ .Files.Get "voting-app-realm.json" | indent 4 }}
