apiVersion: v1
kind: Secret
metadata:
  name: keycloak-initial-admin
  namespace: {{ .Release.Namespace }}
  labels:
    app: keycloak
type: Opaque
stringData:
  password: {{ .Values.adminPassword | default "TempAdmin123!" | quote }}
