apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-password
  namespace: voting
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: postgres-password
  data:
    - secretKey: postgres-password
      remoteRef:
        key: {{ .Values.postgresPassword.secretKey }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: cloudflare-api-token
  data:
    - secretKey: api-token
      remoteRef:
        key: {{ .Values.cloudflareApiToken.secretKey }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: cloudflare-api-token
  data:
    - secretKey: api-token
      remoteRef:
        key: {{ .Values.cloudflareApiToken.secretKey }}
    - secretKey: cloudflare_api_token
      remoteRef:
        key: {{ .Values.cloudflareApiToken.secretKey }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: repo-voting-app-gitops
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: repo-voting-app-gitops
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: https://github.com/ybojko/voting-app-gitops.git
        username: ybojko
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.githubToken.secretKey }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oauth-creds
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: grafana-oauth-creds
  data:
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.grafanaOauth.secretKey }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-password
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: postgres-password
  data:
    - secretKey: postgres-password
      remoteRef:
        key: {{ .Values.postgresPassword.secretKey }}
