replicaCount: 1

image:
  repository: ghcr.io/ybojko/voting-app-vote
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30080

env:
  REDIS_HOST: redis
  REDIS_PORT: "6379"

resources: {}
