replicaCount: 1

image:
  repository: ghcr.io/ybojko/voting-app-vote
  tag: v2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hostname: vote.redf1ag.xyz

env:
  REDIS_HOST: redis
  REDIS_PORT: "6379"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

imagePullSecrets: []
