replicaCount: 1

image:
  repository: ghcr.io/ybojko/voting-app-vote
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

httproute:
  enabled: true
  gatewayName: voting-app-gateway
  gatewayNamespace: voting
  hostname: vote.redf1ag.xyz

env:
  REDIS_HOST: redis
  REDIS_PORT: "6379"

resources: {}
