apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vote.name" . }}
  labels:
    {{- include "vote.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vote.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vote.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
