{{- if .Values.ingress.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "vote.name" . }}-route
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vote.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: voting-gateway
      namespace: voting
  hostnames:
    - {{ .Values.ingress.hostname | quote }}
  rules:
    - backendRefs:
        - name: {{ include "vote.name" . }}
          port: {{ .Values.service.port }}
{{- end }}
