gateway:
  name: voting-app-gateway
  namespace: voting

listeners:
  https:
    enabled: false
    port: 443
    certificateSecret: voting-app-tls
    acmCertificateArn: ""

certificate:
  name: voting-app-tls
  issuerName: letsencrypt-prod
  issuerKind: ClusterIssuer
  domains:
    - vote.redf1ag.xyz
    - result.redf1ag.xyz
    - grafana.redf1ag.xyz
    - keycloak.redf1ag.xyz
