{{- if not .Values.cloudflare.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  labels:
    app.kubernetes.io/component: cluster-issuer
type: Opaque
stringData:
  api-token: {{ .Values.cloudflare.apiToken }}
{{- end }}
