apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-lb-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.11.x
    helm:
      values: |
        clusterName: voting-app-eks
        serviceAccount:
          create: true
          name: aws-load-balancer-controller
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::179686849870:role/voting-app-eks-lb-controller
        enableServiceMutatorWebhook: false
        enableGatewayApiController: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
