apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/ybojko/voting-app-gitops.git
    targetRevision: HEAD
    path: helm-charts/cluster-issuer
    helm:
      values: |
        cloudflare:
          email: yurkabojko@gmail.com
          existingSecret: cloudflare-api-token
        issuer:
          email: yurkabojko@gmail.com
          server: https://acme-staging-v02.api.letsencrypt.org/directory
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
