apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-cluster-secret-store
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/ybojko/voting-app-gitops.git
    targetRevision: HEAD
    path: helm-charts/eso-cluster-secret-store
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
