apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: postgresql
    targetRevision: 18.7.11
    helm:
      values: |
        auth:
          existingSecret: postgres-password
          database: postgres
          postgresPassword: ""
        primary:
          persistence:
            size: 1Gi
            storageClass: gp2
          pgHbaConfiguration: |-
            host all all 0.0.0.0/0 scram-sha-256
            host all all ::/0 scram-sha-256
            local all all scram-sha-256
  destination:
    server: https://kubernetes.default.svc
    namespace: voting
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
