apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 16.6.7
    helm:
      values: |
        auth:
          postgresPassword: postgres
          database: postgres
        primary:
          persistence:
            size: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: voting
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
