apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: result
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/ybojko/voting-app-gitops.git
    targetRevision: HEAD
    path: helm-charts/result
    helm:
      values: |
        replicaCount: 1
        image:
          repository: ghcr.io/ybojko/voting-app-result
          tag: v1
          pullPolicy: IfNotPresent
        service:
          type: ClusterIP
          port: 80
        ingress:
          enabled: true
          hostname: result.redf1ag.xyz
        env:
          DB_HOST: postgres-postgresql
          DB_PORT: "5432"
          DB_USER: postgres
          DB_NAME: postgres
        secretEnv:
          DB_PASSWORD:
            secretName: postgres-password
            key: postgres-password
        imagePullSecrets:
          - name: ghcr-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: voting
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
