apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vote
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/ybojko/voting-app-gitops.git
    targetRevision: HEAD
    path: helm-charts/vote
    helm:
      values: |
        replicaCount: 1
        image:
          repository: 522868276919.dkr.ecr.eu-central-1.amazonaws.com/voting-app-vote
          tag: latest
          pullPolicy: IfNotPresent
        service:
          type: ClusterIP
          port: 80
        ingress:
          enabled: true
          hostname: vote.redf1ag.xyz
        env:
          REDIS_HOST: redis
          REDIS_PORT: "6379"
  destination:
    server: https://kubernetes.default.svc
    namespace: voting
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
