apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/ybojko/voting-app-gitops.git
    targetRevision: HEAD
    path: helm-charts/gateway
    helm:
      values: |
        gatewayClass:
          name: eg
          controllerName: gateway.envoyproxy.io/gatewayclass-controller
        gateway:
          name: voting-gateway
          namespace: voting
          hostname: "*.voting.local"
          tlsSecret: local-tls
  destination:
    server: https://kubernetes.default.svc
    namespace: voting
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
