apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/ybojko/voting-app-gitops.git
    targetRevision: HEAD
    path: helm-charts/keycloak
    helm:
      values: |
        replicaCount: 1
        image:
          repository: quay.io/keycloak/keycloak
          tag: "26.1"
          pullPolicy: IfNotPresent
        service:
          type: ClusterIP
          port: 8080
        persistence:
          enabled: true
          size: 1Gi
          storageClass: standard
        hostname: keycloak.voting.local
        database:
          vendor: postgres
          host: postgres-postgresql.voting.svc.cluster.local
          port: 5432
          database: keycloak
          username: postgres
          existingSecret: postgres-password
          existingSecretPasswordKey: postgres-password
        resources:
          requests:
            cpu: 100m
            memory: 768Mi
          limits:
            cpu: 500m
            memory: 1536Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
