apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-route
  namespace: keycloak
spec:
  parentRefs:
    - name: voting-gateway
      namespace: voting
  hostnames:
    - {{ .Values.hostname | quote }}
  rules:
    - backendRefs:
        - name: {{ .Values.serviceName }}
          port: {{ .Values.servicePort }}
