replicaCount: 1
image:
  repository: quay.io/keycloak/keycloak
  tag: "26.1"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
persistence:
  enabled: false
  size: 1Gi
  storageClass: gp2
adminPassword: "TempAdmin123!"
resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
